**Tabalho Prático 1 – Análise de Crédito**

**Alunos:

GIOVANNI SURIANI FERREIRA

JORGE ALIOMAR TROCOLI ABDON DANTAS**

**Enunciado(s):**

Cada dupla deve escolher um problema no Kaggle. Elaborar uma solução e apresentar para turma no dia da entrega. A solução da dupla deve ser entregue no Moodle em um Python Notebook. Especificamente, a dupla deve:
- Pesquisar um problema interessante no Kaggle que envolva dados tabulares/estruturados;
- Realizar uma análise exploratória dos dados da competição. Isto é, visualizar os dados, tentar identificar dados faltantes, instâncias ruidosas e tendências nos dados;
- Entender e implementar a métrica de avaliação da competição;
- Implementar uma solução simples para o problema da competição para gerar um baseline (isto é, o desempenho mínimo que o sua abordagem deve alcançar);
- Estudar soluções para problemas semelhantes ao da competição escolhida. A dupla pode pesquisar, por exemplo, em artigos acadêmicos, artigos técnicos da Internet e o no próprio Kaggle;
- Implementar diferentes abordagens para a competição e reportar o desempenho de cada abordagem implementada;
- Realizar uma avaliação de parâmetro (hyperparameter tuning) das abordagens escolhidas para o problema. Para realizar a avaliação dos parâmetros você pode utilizar GridSearchCV ou Optuna.
- Além de outras abordagens, a dupla deve:
    - Propor pelo menos uma abordagem que envolva meta-learning. Ou seja, a dupla deve propor uma forma diferente de combinar vários modelos. Por exemplo, utilize a abordagem do Random Forest, porém com vários classificadores ou invés de utilizar apenas Árvores de Decisão.
- Para cada abordagem apresentada, a dupla deve apresentar:
    - desempenho no conjunto de treino, o desempenho deve ser medido com uma validação cruzada com 10 folds (10-fold cross-validation).
    - desempenho no conjunto de teste reportado pelo Kaggle

# DESAFIO E PROBLEMA ESCOLHIDO
Home Credit Default Risk (https://www.kaggle.com/competitions/home-credit-default-risk)

O desafio consiste em melhorar os modelos preditivos, da HOME CREDIT, de crédito voltados a pessoas sem histórico bancário. Utilizando dados alternativos como registros de telecomunicações e transações, a empresa quer garantir que mais pessoas aptas recebam empréstimos justos e sustentáveis. O desafio propõe que os participantes usem técnicas de ciência de dados e machine learning para prever com mais precisão a capacidade de pagamento dos clientes.

O conjunto de dados contém informações detalhadas sobre o histórico financeiro de clientes da Home Credit e de outras instituições, com o objetivo de prever a capacidade de pagamento de novos empréstimos.

 - application_{train|test}.csv: Esta é a tabela principal, dividida em dois arquivos: Treinamento (com a variável TARGET) e Teste (sem TARGET). Contém dados estáticos de todas as solicitações de empréstimo. Cada linha representa um empréstimo.

 - bureau.csv: Todos os créditos anteriores dos clientes fornecidos por outras instituições financeiras, reportados ao Bureau de Crédito (apenas para clientes com empréstimo na amostra). Cada linha representa um crédito anterior registrado antes da data da aplicação atual.

 - bureau_balance.csv: Saldos mensais dos créditos anteriores no Bureau de Crédito. Cada linha representa um mês de histórico para cada crédito anterior — ou seja, número de empréstimos * número de créditos anteriores * número de meses com histórico disponível.

 - POS_CASH_balance.csv: Saldos mensais dos empréstimos anteriores no ponto de venda (POS) ou empréstimos em dinheiro que o cliente teve com a Home Credit. Uma linha por mês de histórico de cada crédito anterior relacionado ao empréstimo na amostra.

 - credit_card_balance.csv: Saldos mensais dos cartões de crédito anteriores que o cliente tem com a Home Credit. Formato similar ao POS_CASH_balance, mas para cartões de crédito.

 - previous_application.csv: Todas as solicitações anteriores de empréstimos feitas à Home Credit por clientes com empréstimos na amostra atual. Uma linha por solicitação anterior.

 - installments_payments.csv: Histórico de pagamentos de créditos anteriores concedidos pela Home Credit. Inclui: a) uma linha para cada pagamento feito, e b) uma linha para cada parcela não paga. Cada linha representa um pagamento ou uma parcela de um crédito anterior.

 - HomeCredit_columns_description.csv: Arquivo com a descrição das colunas de todos os outros arquivos do conjunto de dados.

 As tabelas podem se relacionar conforme imagem abaixo:

 ![image.png](attachment:image.png)




# PREPARAÇÃO DA BASE DE DADOS - Todos os dados

In [1]:
#Importando Bibliotecas Pandas e Numpy
import pandas as pd
import numpy as np
import os, sys


#Otimizador Giovanni
from sklearnex import patch_sklearn
patch_sklearn()


CSV_PATH = "/home/gi/Desktop/Semestre8/Inteligencia_Computacional/TP1_csvs" # Path Giovanni
# CSV_PATH = "E:/Documentos/CEFET/OneDrive/Documentos/2ECOM067_INTELIGENCIA-COMPUTACIONAL-I_T01/TP1/bases/" # Path Jorge

Intel(R) Extension for Scikit-learn* enabled (https://github.com/uxlfoundation/scikit-learn-intelex)


In [2]:
#Desabilitando os warnings
import warnings
warnings.simplefilter("ignore")

In [3]:
#Carregando Base de dados principal - Treino
df_train = pd.read_csv(f"{CSV_PATH}/application_train.csv")
df_01 = pd.read_csv(f"{CSV_PATH}/df_01.csv")
df_02 = pd.read_csv(f"{CSV_PATH}/df_02.csv")
df_03 = pd.read_csv(f"{CSV_PATH}/df_03.csv")
df_04 = pd.read_csv(f"{CSV_PATH}/df_04.csv")

y_train = df_train['TARGET']


In [4]:
df_01.info(max_cols=1000)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 140 columns):
 #    Column                        Non-Null Count   Dtype  
---   ------                        --------------   -----  
 0    TARGET                        307511 non-null  int64  
 1    NAME_CONTRACT_TYPE            307511 non-null  int64  
 2    CODE_GENDER                   307511 non-null  int64  
 3    FLAG_OWN_CAR                  307511 non-null  int64  
 4    FLAG_OWN_REALTY               307511 non-null  int64  
 5    CNT_CHILDREN                  307511 non-null  int64  
 6    AMT_INCOME_TOTAL              307511 non-null  float64
 7    AMT_CREDIT                    307511 non-null  float64
 8    AMT_ANNUITY                   307499 non-null  float64
 9    AMT_GOODS_PRICE               307233 non-null  float64
 10   NAME_TYPE_SUITE               307511 non-null  int64  
 11   NAME_INCOME_TYPE              307511 non-null  int64  
 12   NAME_EDUCATION_TYPE         

# PREPARAÇÃO DA BASE DE DADOS - Amostra

Como as bases de dados original tem muitos valores, e as simulações subsequentes podem demorar muitas horas, realizar-se-a uma amostra aleatória das bases para treinamento e teste.
Para deixar as bases com os mesmos SK_ID_CURR, faz-se primeiramente a amostragem via df_01, e para os demais dataframes selecionamos os valores dos atributos (colunas) do SK_ID_CURR do df_01. Isso faz com que o y_train seja único para os 4 df_x.


In [5]:
def generate_all_xtrain_ytrain(df_01, df_02, df_03, df_04):
    df_01_train = df_01.sample(frac=0.1, random_state=42)  # Seleciona 10% do DataFrame
    df_02_train = df_02.sample(frac=0.1, random_state=42)  # Seleciona 10% do DataFrame
    df_03_train = df_03.sample(frac=0.1, random_state=42)  # Seleciona 10% do DataFrame
    df_04_train = df_04.sample(frac=0.1, random_state=42)  # Seleciona 10% do DataFrame

    #Divisão treino
    X_train_df_01 = df_01_train.drop(columns={"TARGET"})
    y_train_df_01 = df_01_train["TARGET"]
    X_train_df_02 = df_02_train.drop(columns={"TARGET"})
    y_train_df_02 = df_02_train["TARGET"]
    X_train_df_03 = df_03_train.drop(columns={"TARGET"})
    y_train_df_03 = df_03_train["TARGET"]
    X_train_df_04 = df_04_train.drop(columns={"TARGET"})
    y_train_df_04 = df_04_train["TARGET"]
    return  X_train_df_01, y_train_df_01, X_train_df_02, y_train_df_02, X_train_df_03, y_train_df_03, X_train_df_04, y_train_df_04

In [6]:
#Amostra df_01_train
df_01_train = df_01.sample(frac=0.1, random_state=42)  # Seleciona 10% do DataFrame


#Divisão treino
X_train_df_01 = df_01_train.drop(columns={"TARGET"})
y_train_df_01 = df_01_train["TARGET"]

# 1. Treinamento Individual dos Classificadores

In [5]:
#Importanto as Bibliotecas dos classificadores
from xgboost import XGBClassifier, XGBRegressor
from lightgbm import LGBMClassifier, LGBMRegressor
from catboost import CatBoostClassifier, CatBoostRegressor, Pool
from sklearn.linear_model import LogisticRegression

# Importando biblioteca de clone
from sklearn.base import clone

# Importando stratified k-fold
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

### Avaliando o desempenho dos classificadores

In [6]:
import four_dataframes_from1 as fd
df_train = pd.read_csv(f"{CSV_PATH}/application_train.csv")
df_01, df_02, df_03, df_04 = fd.four_dataframes_from_one(df_train, sample=0.5)
y_train = df_01["TARGET"]
x_1 = df_01.drop(columns={"TARGET"})
x_2 = df_02.drop(columns={"TARGET"})
x_3 = df_03.drop(columns={"TARGET"})
x_4 = df_04.drop(columns={"TARGET"})

Intel(R) Extension for Scikit-learn* enabled (https://github.com/uxlfoundation/scikit-learn-intelex)


df_test shape (307511, 122), df_01 shape (153756, 140), df_02 shape (153756, 165), df_03 shape (153756, 165), df_04 shape (153756, 180)


In [7]:
# Confirmando que todos os targets sao os mesmos
if not df_01["TARGET"].empty:
    if df_01["TARGET"].equals(df_02["TARGET"]) and df_01["TARGET"].equals(df_03["TARGET"]) and df_01["TARGET"].equals(df_04["TARGET"]):
        print("Os dataframes possuem a mesma coluna TARGET")

Os dataframes possuem a mesma coluna TARGET


In [ ]:
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from sklearn.base import clone
import numpy as np
xgb = XGBClassifier()

# Verificando so com o primeiro df
for train_index, test_index in skf.split(x_1, y_train):
    # Divide os dados de teste
    y_test_fold = y_train.iloc[test_index]
    x_1_test = x_1.iloc[test_index]
    xgb.fit(x_1.iloc[train_index], y_train.iloc[train_index])
    # Predições de classe (0 ou 1)
    xgb_pred_proba = xgb.predict_proba(x_1_test)[:, 1]  # Probabilidade da classe 1
    roc_auc = roc_auc_score(y_test_fold, xgb_pred_proba)
    print(f"Predição 1:  roc_auc = {roc_auc:.4f}")

    # AUC para predições finais
    # roc_auc = roc_auc_score(y_test_fold, pred_final)
    # roc_auc_scores.append(roc_auc)
    
    # Cada modelo usa um X diferente para prever
    

Predição 1:  roc_auc = 0.7313
Predição 1:  roc_auc = 0.7465
Predição 1:  roc_auc = 0.7445
Predição 1:  roc_auc = 0.7291
Predição 1:  roc_auc = 0.7183


Exception ignored on calling ctypes callback function: <bound method DataIter._next_wrapper of <xgboost.data.SingleBatchInternalIter object at 0x7ef0bef4f460>>
Traceback (most recent call last):
  File "/home/gi/.local/lib/python3.10/site-packages/xgboost/core.py", line 585, in _next_wrapper
    def _next_wrapper(self, this: None) -> int:  # pylint: disable=unused-argument
KeyboardInterrupt: 


In [ ]:
""" from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, precision_score, recall_score
from sklearn.base import clone
import numpy as np

def treinar_avaliar_com_grid_modelo_meta_individual(model, param_grid, X_1, X_2, X_3, X_4, y_train, nome):
    roc_auc_scores = []
    pred_final = []

    for fold, (train_index, test_index) in enumerate(skf.split(X_1, y_train)):
        y_test_fold = y_train.iloc[test_index]
        y_train_fold = y_train.iloc[train_index]

        # Dados de treino/teste para cada representação
        X1_train, X1_test = X_1.iloc[train_index], X_1.iloc[test_index]
        X2_train, X2_test = X_2.iloc[train_index], X_2.iloc[test_index]
        X3_train, X3_test = X_3.iloc[train_index], X_3.iloc[test_index]
        X4_train, X4_test = X_4.iloc[train_index], X_4.iloc[test_index]

        # Aplica GridSearchCV para cada modelo individual
        def gridsearch(X_train, y_train):
            gs = GridSearchCV(clone(model), param_grid, scoring='roc_auc', cv=5, n_jobs=-1, verbose=0)
            gs.fit(X_train, y_train)
            print(f"Melhor modelo: {gs.best_estimator_}")
            print(f"Melhores parâmetros: {gs.best_params_}")
            return gs.best_estimator_

        m1 = gridsearch(X1_train, y_train_fold)
        m2 = gridsearch(X2_train, y_train_fold)
        m3 = gridsearch(X3_train, y_train_fold)
        m4 = gridsearch(X4_train, y_train_fold)

        # Previsões
        p1 = (m1.predict_proba(X1_test)[:, 1] >= 0.5).astype(int)
        p2 = (m2.predict_proba(X2_test)[:, 1] >= 0.5).astype(int)
        p3 = (m3.predict_proba(X3_test)[:, 1] >= 0.5).astype(int)
        p4 = (m4.predict_proba(X4_test)[:, 1] >= 0.5).astype(int)

        # Avaliação individual
        print(f"[Fold {fold+1}]")
        for i, (p, label) in enumerate(zip([p1, p2, p3, p4], ['1', '2', '3', '4'])):
            print(f"Predição {label}:  f1 = {f1_score(y_test_fold, p):.4f}, roc_auc = {roc_auc_score(y_test_fold, p):.4f}, acc = {accuracy_score(y_test_fold, p):.4f}, recall = {recall_score(y_test_fold, p):.4f}")

        # Ensemble simples (votação)
        preds = np.column_stack([p1, p2, p3, p4])
        pred_final = (preds.sum(axis=1) >= 2).astype(int)  # maioria simples

        # Avaliação final
        roc_auc = roc_auc_score(y_test_fold, pred_final)
        roc_auc_scores.append(roc_auc)

        accuracy = accuracy_score(y_test_fold, pred_final)
        f1 = f1_score(y_test_fold, pred_final)

    print(f"Predição final média: accuracy = {accuracy:.4f}, f1 = {f1:.4f}, roc_auc_mean = {np.mean(roc_auc_scores):.4f}, std = {np.std(roc_auc_scores):.4f}")
    return m1, m2, m3, m4 """


In [17]:
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, precision_score, recall_score
from sklearn.base import clone
import numpy as np

def treinar_avaliar_modelo_meta_individual(model, X_1, X_2, X_3, X_4, y_train, nome):
    roc_auc_scores = []
    pred_final = []
    for train_index, test_index in skf.split(X_1, y_train):
        # Divide os dados de teste
        y_test_fold = y_train.iloc[test_index]

        # Dados de teste para cada modelo
        X1_test = X_1.iloc[test_index]
        X2_test = X_2.iloc[test_index]
        X3_test = X_3.iloc[test_index]
        X4_test = X_4.iloc[test_index]

        # Clona e treina os modelos em seus respectivos datasets
        m1 = clone(model).fit(X_1.iloc[train_index], y_train.iloc[train_index])
        m2 = clone(model).fit(X_2.iloc[train_index], y_train.iloc[train_index])
        m3 = clone(model).fit(X_3.iloc[train_index], y_train.iloc[train_index])
        m4 = clone(model).fit(X_4.iloc[train_index], y_train.iloc[train_index])

        # Obtém as probabilidades da classe positiva
        p1 = (m1.predict_proba(X1_test)[:, 1] >= 0.5).astype(int)
        p2 = (m2.predict_proba(X2_test)[:, 1] >= 0.5).astype(int)
        p3 = (m3.predict_proba(X3_test)[:, 1] >= 0.5).astype(int)
        p4 = (m4.predict_proba(X4_test)[:, 1] >= 0.5).astype(int)

        # Avaliação individual opcional
        print(f"Predição 1:  f1_auc = {f1_score(y_test_fold, p1):.4f}, roc_auc = {roc_auc_score(y_test_fold, p1):.4f}, precision = {accuracy_score(y_test_fold, p1):.4f}, recall = {recall_score(y_test_fold, p1):.4f}")
        print(f"Predição 2:  f1_auc = {f1_score(y_test_fold, p2):.4f}, roc_auc = {roc_auc_score(y_test_fold, p2):.4f}, precision = {accuracy_score(y_test_fold, p2):.4f}, recall = {recall_score(y_test_fold, p2):.4f}")
        print(f"Predição 3:  f1_auc = {f1_score(y_test_fold, p3):.4f}, roc_auc = {roc_auc_score(y_test_fold, p3):.4f}, precision = {accuracy_score(y_test_fold, p3):.4f}, recall = {recall_score(y_test_fold, p3):.4f}")
        print(f"Predição 4:  f1_auc = {f1_score(y_test_fold, p4):.4f}, roc_auc = {roc_auc_score(y_test_fold, p4):.4f}, precision = {accuracy_score(y_test_fold, p4):.4f}, recall = {recall_score(y_test_fold, p4):.4f}")

        # Ensemble: 
        preds = np.column_stack([p1, p2, p3, p4])
        print(f"{preds}")
        pred_final = (preds.sum(axis=1) >= 1).astype(int)

        # Avaliação do ensemble
        roc_auc = roc_auc_score(y_test_fold, pred_final)
        roc_auc_scores.append(roc_auc)
        
        accuracy = accuracy_score(y_test_fold, pred_final)
        f1 = f1_score(y_test_fold, pred_final)
    print(f"Predição final:  accuracy_auc = {accuracy:.4f}")
    print(f"Predição final:  f1_auc = {f1:.4f}")
    #print(f"{nome}: roc_auc_mean = {np.mean(roc_auc_scores):.4f}, desvio padrão = {np.std(roc_auc_scores):.4f}")
    return m1, m2, m3, m4

In [18]:
xgboost_params = {'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 100, 'subsample': 0.8}
lgbm_params = {'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 100, 'subsample': 0.8}
catboost_params = {'depth': 4, 'iterations': 150, 'l2_leaf_reg': 3, 'learning_rate': 0.1}

xgb_class = XGBClassifier(**xgboost_params)
m1,m2,m3,m4 = treinar_avaliar_modelo_meta_individual(xgb_class, x_1, x_2, x_3, x_4, y_train, "XGB")

Predição 1:  f1_auc = 0.0330, roc_auc = 0.5081, precision = 0.9199, recall = 0.0169
Predição 2:  f1_auc = 0.0300, roc_auc = 0.5075, precision = 0.9201, recall = 0.0153
Predição 3:  f1_auc = 0.0284, roc_auc = 0.5070, precision = 0.9199, recall = 0.0145
Predição 4:  f1_auc = 0.0330, roc_auc = 0.5082, precision = 0.9201, recall = 0.0169
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Predição 1:  f1_auc = 0.0345, roc_auc = 0.5084, precision = 0.9198, recall = 0.0177
Predição 2:  f1_auc = 0.0313, roc_auc = 0.5075, precision = 0.9195, recall = 0.0161
Predição 3:  f1_auc = 0.0313, roc_auc = 0.5076, precision = 0.9196, recall = 0.0161
Predição 4:  f1_auc = 0.0328, roc_auc = 0.5078, precision = 0.9194, recall = 0.0169
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Predição 1:  f1_auc = 0.0299, roc_auc = 0.5073, precision = 0.9197, recall = 0.0153
Predição 2:  f1_auc = 0.0252, roc_auc = 0.5061, precision = 0.9195, recall = 0.0129
Predição 3:  f1_

In [12]:
def modelo_meta_individual(X_1, X_2, X_3, X_4, m1, m2, m3, m4):
    roc_auc_scores = []
    pred_final = []

    # Obtém as probabilidades da classe positiva
    p1 = (m1.predict_proba(X_1)[:, 1] >= 0.5).astype(int)
    p2 = (m2.predict_proba(X_2)[:, 1] >= 0.5).astype(int)
    p3 = (m3.predict_proba(X_3)[:, 1] >= 0.5).astype(int)
    p4 = (m4.predict_proba(X_4)[:, 1] >= 0.5).astype(int)

    # Ensemble: 
    preds = np.column_stack([p1, p2, p3, p4])
    pred_final = (preds.sum(axis=1) >= 1).astype(int)

    return pred_final
    

In [19]:
df_test = pd.read_csv(f"{CSV_PATH}/application_test.csv")
df_01_test, df_02_test, df_03_test, df_04_test = fd.four_dataframes_from_one(df_test)

df_test shape (48744, 121), df_01 shape (48744, 139), df_02 shape (48744, 164), df_03 shape (48744, 164), df_04 shape (48744, 179)


In [20]:
y_pred_kaggle = modelo_meta_individual(df_01_test,df_02_test,df_03_test,df_04_test,m1,m2,m3,m4)

In [21]:
# Criando o DataFrame de submissão
submission_df = pd.DataFrame({
    'SK_ID_CURR': df_test['SK_ID_CURR'],
    'TARGET': y_pred_kaggle
})
# Salvando o DataFrame em um arquivo CSV
submission_df.to_csv(f"{CSV_PATH}/submission.csv", index=False)

#RESULTADOS

![image.png](attachment:image.png)

Como informado anteriormente, devido a grande quantidade de dados e limitações estruturais e de capacidade do notebook não foi possível criar uma base única com as devidas mesclagens. Como alternativa, montou-se 4 Data Frames (df_01 a df_04) com join de bases diferentes, mas tento uma base principal. Mas como a base inicial ainda continuava grande, optou-se por amostrar em 20% a base original, aleatoriamente. Cada Data Frame, gerado aleatoriamente, foi utilizado para treinar modelos dos classificadores da prática (XGBOOST, LIGHTGBM e CATBOOST), tendo como métrica de avaliação o ROC-UAC.

Para o df_01 obteve-se como resultados:

![image.png](attachment:image.png)


Para o df_02 obteve-se como resultados:

![image-2.png](attachment:image-2.png)


Para o df_03 obteve-se como resultados:

![image-3.png](attachment:image-3.png)


Para o df_04 obteve-se como resultados:

![image-4.png](attachment:image-4.png)


Observou-se que os modelos que sairam melhor foram o XGBOOST, LIGHTGBM, ambos com resultados próximos. Já o CATBOOST foi o de pior resultado em todos os dataframes.

No intuito de agregar os diferentes modelos para uma melhor resposta, utilizou-se a estratégia a combinação com VotingClassifier (Hard e Soft) e StackingClassifier. A combinação consiste na combinação de modelos, gerando um novo modelo, e com este novo modelo há o treinamento de uma base. Como nossa base não foi única, e sim fragmentada nos 4 data frames, optou-se por escolher o df_01 como base para X e y na combinação. A escolha foi feita por entendermos que o df_01 trazia mais informações, no entanto, ficamos com dúvida se está é uma boa e ideal escolha.

Para o VotingClassifier (Hard e Soft) obteve-se os seguintes resultados:

![image-5.png](attachment:image-5.png)

![image-7.png](attachment:image-7.png)

Para o StackingClassifier obteve-se os seguinte resultado

![image-6.png](attachment:image-6.png)

Para ambos os modelos gerados através da combinação houve a predição com o dataframe de test do Kaggle. Gerou-se 2 arquivos . CSV que foram submetidos no Kaggle, obtendo-se os seguintes resultados:

![image-8.png](attachment:image-8.png)

Em comparação com as simulações individuais  observou-se que houve a piora pela combinação do modelos. No entanto, os resultados da combinação foram mais próximos dos resultados após submissão no Kaggle. Isto sugere que os modelos individuais estão mais overfitados. No entanto, tem-se que ponderar que somente 20% de dados ( aproximadamente 66 mil) foram utilizados.


utilizar label encoder